server:
  port: 8190
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    name: miaosha
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1999c719
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver